### ISSUE TITLE
Failed to Upload. Browser getting closed prematurely before the file gets uploaded.

### ISSUE THREAD

**Issue by bendangnuksung** [linouk23/youtube_uploader_selenium#12]
Tried to upload a video file which is of 5 GB. Before the file gets fully uploaded the browser closes after filling all the forms and hence leading to fail in uploading videos. 

I think there should be a check where the browser closes once the file gets uploaded.

**Comment by bendangnuksung** [comment]
It is difficult to know whether the file has been uploaded as there is no such major change in  the UI. To overcome this 1 thing I can think of is using image template matching where it continually take screenshot and check if the text been updated. This is just a suggestion, there might be a better workaround.

**Comment by 7x11x13** [comment]
This should be fixed with #10

**Comment by linouk23** [comment]
Thanks for opening this issue! I think it has been fixed with #10.
