### ISSUE TITLE
ImportError: cannot import name 'By' from 'selenium_firefox.firefox'

### ISSUE THREAD

**Issue by tjtgzxs** [linouk23/youtube_uploader_selenium#17]
Traceback (most recent call last):
  File "upload.py", line 1, in <module>
    from youtube_uploader_selenium import YouTubeUploader
  File "/home/ubuntu/.local/lib/python3.8/site-packages/youtube_uploader_selenium/__init__.py", line 5, in <module>
    from selenium_firefox.firefox import Firefox, By, Keys
ImportError: cannot import name 'By' from 'selenium_firefox.firefox' (/home/ubuntu/.local/lib/python3.8/site-packages/selenium_firefox/firefox.py)

**Comment by ankitsiliconithub** [comment]
from selenium_firefox.firefox import Firefox, By, Keys
Please  remove , By, Keys this line from init.py file

**Comment by shrikant2002** [comment]
but it failed to upload after removing " By, Keys" this line from init.py file
