### ISSUE TITLE
My description as set as title

### ISSUE THREAD

**Issue by keustii** [linouk23/youtube_uploader_selenium#28]
all works fines, 
login, upload, thumbnail, title,
but few time after my title are set, my description overwrite it
anyone know how to fix this ?

**Comment by lalitaalaalitah** [comment]
Change below ```if video_description:```
```
# description_container = self.browser.find(By.XPATH, Constant.DESCRIPTION_CONTAINER)
description_field = self.browser.find_all(By.ID, Constant.TEXTBOX)[1]
# print(len(description_field))
# for each_t in description_field:
#     print(each_t)
# description_field = self.browser.find(By.ID, Constant.TEXTBOX, element=description_container)
```

**Comment by keustii** [comment]
> Change below `if video_description:`
> 
> ```
> # description_container = self.browser.find(By.XPATH, Constant.DESCRIPTION_CONTAINER)
> description_field = self.browser.find_all(By.ID, Constant.TEXTBOX)[1]
> # print(len(description_field))
> # for each_t in description_field:
> #     print(each_t)
> # description_field = self.browser.find(By.ID, Constant.TEXTBOX, element=description_container)
> ```

thx mate

**Comment by domasb2005** [comment]
> 
> 
> Change below `if video_description:`
> 
> ```
> # description_container = self.browser.find(By.XPATH, Constant.DESCRIPTION_CONTAINER)
> description_field = self.browser.find_all(By.ID, Constant.TEXTBOX)[1]
> # print(len(description_field))
> # for each_t in description_field:
> #     print(each_t)
> # description_field = self.browser.find(By.ID, Constant.TEXTBOX, element=description_container)
> ```

I cloned your branch and i am getting this error. 
![image](https://user-images.githubusercontent.com/76450741/113596460-02ddd600-9643-11eb-9227-7214499b43dc.png)

I had same error with master branch too. Close up: 
![image](https://user-images.githubusercontent.com/76450741/113596537-243ec200-9643-11eb-8aac-2e85944deaa0.png)

**Comment by lalitaalaalitah** [comment]
No, you've note copied my code properly. You've to comment out those parts which i did. That means copy the code i provided as it is, don't remove hash or anything else.
