### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'firefox_options'

### ISSUE THREAD

**Issue by kypello** [linouk23/youtube_uploader_selenium#61]
selenium_firefox/firefox.py", line 86, in __init__
self.driver = webdriver.Firefox(firefox_profile=profile, firefox_options=options)
TypeError: __init__() got an unexpected keyword argument 'firefox_options'

Does anyone know what the problem is here?

**Comment by kypello** [comment]
FIXED: I had the wrong version of selenium installed. It has to be 3.8.0 or earlier.

You can use the command "pip install selenium==3.8.0" to get the correct version

**Comment by gartha1** [comment]
> FIXED: I had the wrong version of selenium installed. It has to be 3.8.0 or earlier.
> 
> You can use the command "pip install selenium==3.8.0" to get the correct version

3.141.0 is a bit later, has been mentioned by others here, and firefox still loads with it. So prob better to do

pip install selenium==3.141.0

**Comment by jamesjiayu** [comment]
cool , thanks @gartha1
