### ISSUE TITLE
'NoneType' object has no attribute 'click'

### ISSUE THREAD

**Issue by DouglasDGI** [linouk23/youtube_uploader_selenium#9]
Crash occurs on line 77, which says `title_field.click()` which comes after `title_field = self.browser.find(By.ID, Constant.TEXTBOX)`.

Firefox opens and logs in correctly, but crashes very shortly after.  Here is the full error:
```DEBUG:youtube_uploader_selenium:Attached video ./UploadMe/LUCK.jpg.mp4
'NoneType' object has no attribute 'click'
Traceback (most recent call last):
  File "/home/lostrobot/Automation Stuff/Uploader/YoutubeUploader.py", line 125, in <module>
    was_video_uploaded, video_id = uploader.upload()
  File "/home/lostrobot/.local/lib/python3.8/site-packages/youtube_uploader_selenium/__init__.py", line 47, in upload
    return self.__upload()
  File "/home/lostrobot/.local/lib/python3.8/site-packages/youtube_uploader_selenium/__init__.py", line 77, in __upload
    title_field.click()
AttributeError: 'NoneType' object has no attribute 'click'
```

I am using Ubuntu 20.04.
Thanks for the help in advance.  I only have a few days to get this working, so I would be eternally grateful for a quick reply.

**Comment by freelancesam** [comment]
@DouglasDGI  I think the issue is that it's trying to click an element that isn't there yet.

Go to Constant.py and change:

USER_WAITING_TIME = 5 

So it waits 5 seconds between each action. It's very crudely done, it should wait until the element is visible.

**Comment by 7x11x13** [comment]
The problem is that it doesn't wait after sending the file, and the upload settings dialog isn't open yet. It should work if you wait a few seconds between sending the keys and finding the title field.
https://github.com/linouk23/youtube_uploader_selenium/blob/5b2a4ea4952ee4a81ef21835f313c3f605b7b4eb/youtube_uploader_selenium/__init__.py#L74-L77

**Comment by wonbinbk** [comment]
> The problem is that the find call doesn't wait long enough, and the upload settings dialog isn't open yet. It should work if you sleep a few seconds between sending the keys and finding the title field.
> 
> https://github.com/linouk23/youtube_uploader_selenium/blob/5b2a4ea4952ee4a81ef21835f313c3f605b7b4eb/youtube_uploader_selenium/__init__.py#L74-L77
> 
> Another option would be to increase the timeout for the find function e.g.
> `title_field = self.browser.find(By.ID, Constant.TEXTBOX, timeout=10) `

I can confirm that this fixed this issue. I'm using Manjaro.
However, I met another issue. Below is the log:
`
DEBUG:youtube_uploader_selenium:Selected "NOT_MADE_FOR_KIDS"
DEBUG:youtube_uploader_selenium:Clicked next-button
DEBUG:youtube_uploader_selenium:Clicked another next-button
DEBUG:youtube_uploader_selenium:Made the video PUBLIC
DEBUG:youtube_uploader_selenium:Published the video with video_id = Q0eb3iQATpA
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdd9e0ab490>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1afeb8a0-2bd8-4e56-be62-a50ca0c806b7
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdd9e0ab0a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1afeb8a0-2bd8-4e56-be62-a50ca0c806b7
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdd9dfad310>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1afeb8a0-2bd8-4e56-be62-a50ca0c806b7
[Errno 2] No such file or directory: '/tmp/tmpvaubyxsf'
`
